# Generated by Django 5.2.8 on 2025-12-01 07:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the interest category', max_length=255, unique=True, verbose_name='category name')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the category name', max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, help_text='Brief description of the category', null=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is visible', verbose_name='active')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'interest category',
                'verbose_name_plural': 'interest categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InterestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(db_index=True, help_text='Name of the interest (e.g., Python, React)', max_length=100, verbose_name='interest name')),
                ('slug', models.SlugField(blank=True, help_text='Unique URL-friendly identifier', max_length=200, unique=True, verbose_name='slug')),
                ('is_popular', models.BooleanField(db_index=True, default=False, help_text='Highlight this interest in UI', verbose_name='popular')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='interests.interestcategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'interest',
                'verbose_name_plural': 'interests',
                'ordering': ['interest'],
            },
        ),
        migrations.CreateModel(
            name='UserInterests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('interest', models.ManyToManyField(blank=True, related_name='selected_by_users', to='interests.interestmodel', verbose_name='interests')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_interests', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user interests',
                'verbose_name_plural': 'user interests',
            },
        ),
        migrations.AddIndex(
            model_name='interestmodel',
            index=models.Index(fields=['interest'], name='interests_i_interes_1e11d3_idx'),
        ),
        migrations.AddIndex(
            model_name='interestmodel',
            index=models.Index(fields=['category'], name='interests_i_categor_397a27_idx'),
        ),
        migrations.AddIndex(
            model_name='interestmodel',
            index=models.Index(fields=['is_popular'], name='interests_i_is_popu_4ac14d_idx'),
        ),
        migrations.AddIndex(
            model_name='interestmodel',
            index=models.Index(fields=['-created_at'], name='interests_i_created_6e3910_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interestmodel',
            unique_together={('interest', 'category')},
        ),
    ]
