# Generated by Django 5.2.8 on 2025-11-24 09:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exists'}, max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=30, unique=True, verbose_name='username')),
                ('handlename', models.CharField(error_messages={'unique': 'A user with that handle name already exists.'}, max_length=50, unique=True, verbose_name='handle name')),
                ('avatar', models.ImageField(blank=True, help_text='Profile picture for the user.', null=True, upload_to='avatars/%Y/%m/%d/', verbose_name='avatar')),
                ('cover_photo', models.ImageField(blank=True, help_text='Cover photo or banner for the user profile.', null=True, upload_to='cover_photos/%Y/%m/%d/', verbose_name='cover photo')),
                ('bio', models.TextField(blank=True, help_text='A short description about the user.', max_length=500, verbose_name='bio')),
                ('location', models.CharField(blank=True, help_text="User's location (e.g., city, country).", max_length=100, verbose_name='location')),
                ('birth_date', models.DateField(blank=True, help_text="User's birth date.", null=True, verbose_name='birth date')),
                ('occupation', models.CharField(blank=True, help_text="User's job or profession.", max_length=100, verbose_name='occupation')),
                ('pronouns', models.CharField(blank=True, help_text="User's preferred pronouns (e.g., she/her, he/him, they/them).", max_length=20, verbose_name='pronouns')),
                ('mentorship', models.BooleanField(default=False, help_text='Indicates whether the user offers mentorship.', verbose_name='offers mentorship')),
                ('website', models.URLField(blank=True, help_text="User's personal website.", verbose_name='website')),
                ('github_url', models.URLField(blank=True, help_text="User's GitHub profile URL.", verbose_name='GitHub URL')),
                ('discord_url', models.URLField(blank=True, help_text="User's Discord profile or server invite URL.", verbose_name='Discord URL')),
                ('instagram_url', models.URLField(blank=True, help_text="User's Instagram profile URL.", verbose_name='Instagram URL')),
                ('twitter_url', models.URLField(blank=True, help_text="User's Twitter profile URL.", verbose_name='Twitter URL')),
                ('upwork_url', models.URLField(blank=True, help_text="User's Upwork profile URL.", verbose_name='Upwork URL')),
                ('fiverr_url', models.URLField(blank=True, help_text="User's Fiverr profile URL.", verbose_name='Fiverr URL')),
                ('facebook_url', models.URLField(blank=True, help_text="User's Facebook profile URL.", verbose_name='Facebook URL')),
                ('youtube_url', models.URLField(blank=True, help_text="User's YouTube channel URL.", verbose_name='YouTube URL')),
                ('linkedin_url', models.URLField(blank=True, help_text="User's LinkedIn profile URL.", verbose_name='LinkedIn URL')),
                ('reddit_url', models.URLField(blank=True, help_text="User's Reddit profile URL.", verbose_name='Reddit URL')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='email_verified')),
                ('followers_count', models.PositiveIntegerField(default=0, editable=False)),
                ('following_count', models.PositiveIntegerField(default=0, editable=False)),
                ('friends_count', models.PositiveIntegerField(default=0, editable=False)),
                ('friends', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'email verification token',
                'verbose_name_plural': 'email verification tokens',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_reset_token',
                'indexes': [models.Index(fields=['token'], name='password_re_token_d8eb05_idx')],
            },
        ),
    ]
